# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: xitara.nexus::core.menu.reorder

# Attribute name
nameFrom: display_name

# Model Class name
modelClass: Xitara\Nexus\Models\Menu

# Toolbar widget configuration
toolbar:
    buttons: reorder_toolbar
